In [4]:
import pandas as pd
import numpy as np

import plotly.express as px

# Blitz / Shuffle

In [24]:
bliz_us = pd.read_parquet('data/raw/blizzard_us_season_41.parquet')
bliz_eu = pd.read_parquet('data/raw/blizzard_eu_season_41.parquet')
bliz = pd.concat([bliz_us, bliz_eu], ignore_index=True)

bliz['class_spec'] = bliz['class_name'] + ' ' + bliz['spec_name']

b_dict = {}
for mod in bliz['mode'].unique():
    b_dict[mod] = bliz[bliz['mode'] == mod]
b_dict.keys()

dict_keys(['2v2', 'shuffle', 'rbg', '3v3', 'blitz'])

In [39]:
bliz_s.groupby('class_spec')['rating'].min().max()

np.int64(1511)

In [42]:
bliz_s.groupby('class_spec')['rating'].min().max(), bliz_b.groupby('class_spec')['rating'].min().max()

(np.int64(1511), np.int64(855))

In [188]:
bliz_s[bliz_s['spec_name'] == 'Discipline']

,player_key,region,realm_slug,realm,character_name,class_name,spec_name,mode,rating,rank,season_id,leaderboard,played,won,lost,class_spec
74143,us|illidan|faschisma,us,illidan,illidan,Faschisma,Priest,Discipline,shuffle,2383,1,41,shuffle-priest-discipline,318,184,134,Priest Discipline
74144,us|illidan|faschismo,us,illidan,illidan,Faschismo,Priest,Discipline,shuffle,2359,2,41,shuffle-priest-discipline,537,308,229,Priest Discipline
74145,us|illidan|faschism,us,illidan,illidan,Faschism,Priest,Discipline,shuffle,2339,3,41,shuffle-priest-discipline,716,408,308,Priest Discipline
74146,us|suramar|uncle,us,suramar,suramar,Uncle,Priest,Discipline,shuffle,2321,4,41,shuffle-priest-discipline,147,97,50,Priest Discipline
74147,us|suramar|challengerz,us,suramar,suramar,Challengerz,Priest,Discipline,shuffle,2317,5,41,shuffle-priest-discipline,256,154,102,Priest Discipline
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340946,eu|ravencrest|badpenny,eu,ravencrest,ravencrest,Badpenny,Priest,Discipline,shuffle,1564,4996,41,shuffle-priest-discipline,157,78,79,Priest Discipline
340947,eu|stormscale|wåx,eu,stormscale,stormscale,Wåx,Priest,Discipline,shuffle,1564,4996,41,shuffle-priest-discipline,320,154,166,Priest Discipline
340948,eu|ravencrest|mesmerisme,eu,ravencrest,ravencrest,Mesmerisme,Priest,Discipline,shuffle,1564,4996,41,shuffle-priest-discipline,48,22,26,Priest Discipline
340949,eu|ravencrest|rûbyjane,eu,ravencrest,ravencrest,Rûbyjane,Priest,Discipline,shuffle,1564,4996,41,shuffle-priest-discipline,48,22,26,Priest Discipline
340950,eu|sylvanas|voidowl,eu,sylvanas,sylvanas,Voidowl,Priest,Discipline,shuffle,1564,4996,41,shuffle-priest-discipline,49,21,28,Priest Discipline

In [185]:
bliz_s[(bliz_s['rating'] >= 0) & (bliz_s['rating'] < 1400)]['class_spec'].value_counts()

class_spec
Demon Hunter Havoc        5833
Warrior Fury              5655
Druid Feral               5377
Warlock Destruction       5280
Druid Restoration         5267
Druid Balance             5136
Warlock Demonology        4986
Demon Hunter Devourer     4901
Shaman Restoration        4691
Hunter Marksmanship       4595
Warlock Affliction        4581
Priest Shadow             4127
Mage Fire                 4025
Death Knight Frost        3726
Shaman Enhancement        3678
Shaman Elemental          3374
Monk Windwalker           3312
Evoker Preservation       3274
Rogue Assassination       3075
Hunter Beast Mastery      2894
Paladin Holy              2746
Warrior Arms              2595
Hunter Survival           2494
Priest Holy               2407
Rogue Subtlety            2356
Evoker Devastation        2332
Death Knight Unholy       2239
Rogue Outlaw              2082
Paladin Protection        1626
Mage Frost                1610
Mage Arcane               1477
Druid Guardian            1253
Warrior Protection         635
Monk Mistweaver            594
Monk Brewmaster            592
Death Knight Blood         544
Evoker Augmentation        422
Demon Hunter Vengeance     213
Name: count, dtype: int64

In [88]:
bliz_b['played'].median()

np.float64(9.0)

In [71]:
bliz_before_filters = bliz_s.groupby('class_spec')['rating'].agg(avg_rating='mean',med_rating='median')

bliz_flt = bliz_s[bliz_s['played'] > 10]
bliz_after_filters = bliz_flt.groupby('class_spec')['rating'].agg(avg_rating='mean',med_rating='median')

In [82]:
bliz_b[bliz_b['played'] > 10]

,player_key,region,realm_slug,realm,character_name,class_name,spec_name,mode,rating,rank,season_id,leaderboard,played,won,lost,class_spec
102442,us|sargeras|rankoneblood,us,sargeras,sargeras,Rankoneblood,Death Knight,Blood,blitz,2782,1,41,blitz-deathknight-blood,86,48,38,Death Knight Blood
102443,us|sargeras|priley,us,sargeras,sargeras,Priley,Death Knight,Blood,blitz,2779,2,41,blitz-deathknight-blood,124,68,56,Death Knight Blood
102444,us|tichondrius|horrorz,us,tichondrius,tichondrius,Horrorz,Death Knight,Blood,blitz,2536,3,41,blitz-deathknight-blood,78,52,26,Death Knight Blood
102445,us|twisting-nether|vampyr,us,twisting-nether,twisting-nether,Vampyr,Death Knight,Blood,blitz,2487,4,41,blitz-deathknight-blood,232,123,109,Death Knight Blood
102446,us|black-dragonflight|scotygrippen,us,black-dragonflight,black-dragonflight,Scotygrippen,Death Knight,Blood,blitz,2429,5,41,blitz-deathknight-blood,48,32,16,Death Knight Blood
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228004,us|illidan|billyboyo,us,illidan,illidan,Billyboyo,Warrior,Fury,blitz,575,2220,41,blitz-warrior-fury,13,2,11,Warrior Fury
228005,us|stormrage|gennya,us,stormrage,stormrage,Gennya,Warrior,Fury,blitz,575,2220,41,blitz-warrior-fury,13,2,11,Warrior Fury
228024,us|emerald-dream|thargan,us,emerald-dream,emerald-dream,Thargan,Warrior,Fury,blitz,574,2442,41,blitz-warrior-fury,13,2,11,Warrior Fury
228906,us|windrunner|owlclaw,us,windrunner,windrunner,Owlclaw,Warrior,Fury,blitz,288,2471,41,blitz-warrior-fury,11,1,10,Warrior Fury
228907,us|moon-guard|deathdump,us,moon-guard,moon-guard,Deathdump,Warrior,Fury,blitz,288,2471,41,blitz-warrior-fury,13,1,12,Warrior Fury

In [74]:
bliz_after_filters

                         avg_rating  med_rating
class_spec
Death Knight Blood       620.750000       480.0
Death Knight Frost      1227.602277      1360.0
Death Knight Unholy     1548.551381      1570.0
Demon Hunter Devourer   1327.491405      1456.0
Demon Hunter Havoc      1177.700334      1335.0
Demon Hunter Vengeance   544.732143       359.5
Druid Balance           1135.078902      1262.0
Druid Feral             1129.647652      1272.0
Druid Guardian           764.747845       579.5
Druid Restoration       1306.457644      1371.0
Evoker Augmentation     1150.601770      1312.0
Evoker Devastation      1301.538855      1452.0
Evoker Preservation     1326.879509      1435.0
Hunter Beast Mastery    1497.714401      1601.0
Hunter Marksmanship     1316.571797      1423.0
Hunter Survival         1236.086133      1383.0
Mage Arcane             1119.756281      1237.5
Mage Fire               1260.590157      1398.0
Mage Frost              1577.977800      1579.0
Monk Brewmaster          902.712195       766.0
Monk Mistweaver         1630.967033      1610.0
Monk Windwalker         1389.466444      1503.0
Paladin Holy            1529.918233      1522.0
Paladin Protection       890.948276       672.0
Paladin Retribution     1681.143171      1646.0
Priest Discipline       1723.829668      1696.0
Priest Holy             1458.936575      1558.0
Priest Shadow           1217.051963      1363.0
Rogue Assassination     1254.011099      1399.5
Rogue Outlaw            1320.226428      1476.5
Rogue Subtlety          1496.102114      1525.0
Shaman Elemental        1216.223084      1365.5
Shaman Enhancement      1319.113340      1467.0
Shaman Restoration      1289.581402      1436.0
Warlock Affliction      1266.245404      1411.0
Warlock Demonology      1192.968558      1340.0
Warlock Destruction     1152.567308      1290.0
Warrior Arms            1519.220870      1557.0
Warrior Fury            1195.573179      1330.0
Warrior Protection       617.520202       480.0

In [195]:
bliz[bliz['character_name'] == 'Errhhmm']

,player_key,region,realm_slug,realm,character_name,class_name,spec_name,mode,rating,rank,season_id,leaderboard,played,won,lost,class_spec
84632,us|area-52|errhhmm,us,area-52,area-52,Errhhmm,Priest,Shadow,shuffle,16,3206,41,shuffle-priest-shadow,1,1,0,Priest Shadow
221422,us|area-52|errhhmm,us,area-52,area-52,Errhhmm,Priest,Discipline,blitz,575,4606,41,blitz-priest-discipline,3,2,1,Priest Discipline

# Check-PvP

In [46]:
from wowpvp.constants import CLASS_ID_TO_NAME, SPEC_ID_TO_INFO

In [47]:
check_pvp_eu = pd.read_parquet('data/raw/checkpvp_eu.parquet')
check_pvp_us = pd.read_parquet('data/raw/checkpvp_us.parquet')
check_pvp = pd.concat([check_pvp_eu, check_pvp_us], ignore_index=True)

check_pvp['activeSpecId'] = check_pvp['activeSpecId'].map(SPEC_ID_TO_INFO)
check_pvp['key'] = check_pvp['region'] + '_' + check_pvp['realm'] + '_' + check_pvp['name']

In [51]:
check_pvp[check_pvp['rateatmrbg'] > 0]

,id,lastModified,name,realm,region,class,activeSpecId,race,faction,gender,...,ratioLoseRbg,nombreRecherche,twitch,scoreArena,scoreRBG,estimatedArenaRank1,estimatedBattlegroundRank1,accountAlgo,ranking,key
11,2640678,1778518647,Aight,Aegwynn,eu,12,"(Demon Hunter, Devourer)",4,1,0,...,3,851,NaN,932,1384,False,False,2640678,36743,eu_Aegwynn_Aight
117,6577541,1778619813,Cybermieze,Aegwynn,eu,1,"(Warrior, Arms)",37,1,1,...,9,177,NaN,1553,1883,False,False,6577541,9367,eu_Aegwynn_Cybermieze
145,3120009,1778368268,Djferál,Aegwynn,eu,11,"(Druid, Feral)",4,1,1,...,4,1753,NaN,2332,1926,False,False,03120009,4394,eu_Aegwynn_Djferál
227,408165,1778411910,Gogaa,Aegwynn,eu,3,"(Hunter, Beast Mastery)",4,1,1,...,14,144,,1570,1902,False,False,408165,20248,eu_Aegwynn_Gogaa
228,6159480,1776888423,Goglla,Aegwynn,eu,6,"(Death Knight, Unholy)",34,1,1,...,1,120,NaN,1729,1186,False,False,6159480,21026,eu_Aegwynn_Goglla
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78566,2443289,1776299296,Avante,Zuluhed,us,2,"(Paladin, Holy)",1,1,0,...,47,83,NaN,1130,1562,False,False,2443289,30299,us_Zuluhed_Avante
78570,6659777,1778516707,Beary,Zuluhed,us,3,"(Hunter, Beast Mastery)",2,0,1,...,1,18,NaN,1450,701,False,False,6659777,7329,us_Zuluhed_Beary
78581,6578953,1777751667,Cryptson,Zuluhed,us,3,"(Hunter, Marksmanship)",4,1,0,...,57,16,NaN,1016,1593,False,False,6578953,26373,us_Zuluhed_Cryptson
78584,1960620,1777183613,Deluxee,Zuluhed,us,5,"(Priest, Holy)",1,1,1,...,1,83,NaN,1906,831,False,False,1960620,22049,us_Zuluhed_Deluxee
78617,4519529,1775889967,Retrohammer,Zuluhed,us,2,"(Paladin, Holy)",1,1,0,...,0,56,NaN,2145,915,False,False,4519529,8086,us_Zuluhed_Retrohammer

In [196]:
check_pvp

,id,lastModified,name,realm,region,class,activeSpecId,race,faction,gender,...,ratioLoseRbg,nombreRecherche,twitch,scoreArena,scoreRBG,estimatedArenaRank1,estimatedBattlegroundRank1,accountAlgo,ranking,key
0,7471197,1776507454,Aberhøly,Aegwynn,eu,2,"(Paladin, Retribution)",1,1,1,...,0,23,NaN,1204,860,False,False,7471197,37824,eu_Aegwynn_Aberhøly
1,7346005,1778152773,Acciao,Aegwynn,eu,5,"(Priest, Shadow)",10,0,0,...,0,24,NaN,1764,400,False,False,7377648,15802,eu_Aegwynn_Acciao
2,398520,1777242563,Acerà,Aegwynn,eu,2,"(Paladin, Retribution)",1,1,1,...,0,161,,1714,1060,False,False,398520,6818,eu_Aegwynn_Acerà
3,395537,1776851864,Actîonhans,Aegwynn,eu,11,"(Druid, Restoration)",4,1,1,...,0,326,,1940,614,False,False,0395537,36323,eu_Aegwynn_Actîonhans
4,314834,1777644899,Adq,Aegwynn,eu,4,"(Rogue, Subtlety)",4,1,1,...,0,7199,,2955,1523,False,False,314834,1536,eu_Aegwynn_Adq
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77739,7390399,1778270478,Wrotten,Zuluhed,us,9,"(Warlock, Affliction)",29,1,0,...,0,23,NaN,1108,680,False,False,7390399,13499,us_Zuluhed_Wrotten
77740,7655233,1777694167,Xoono,Zuluhed,us,8,"(Mage, Frost)",4,1,1,...,0,1,NaN,863,0,False,False,7655233,29928,us_Zuluhed_Xoono
77741,2505964,1776905854,Zeeasyez,Zuluhed,us,3,"(Hunter, Marksmanship)",2,0,0,...,0,16,NaN,572,360,False,False,2505964,28252,us_Zuluhed_Zeeasyez
77742,4137438,1775459722,Zeeral,Zuluhed,us,2,"(Paladin, Retribution)",10,0,0,...,0,53,NaN,1652,360,False,False,4137438,19310,us_Zuluhed_Zeeral
77743,5836974,1775496572,Zerall,Zuluhed,us,2,"(Paladin, Retribution)",10,0,0,...,0,47,NaN,1574,360,False,False,5836974,18424,us_Zuluhed_Zerall

In [183]:
check_pvp[(check_pvp['rateatm2v2'] > 0)]['activeSpecId'].value_counts()

activeSpecId
(Priest, Discipline)         2847
(Monk, Mistweaver)           2205
(Rogue, Subtlety)            1857
(Paladin, Retribution)       1856
(Mage, Frost)                1848
(Monk, Windwalker)           1728
(Priest, Holy)               1661
(Paladin, Holy)              1590
(Warrior, Arms)              1456
(Hunter, Beast Mastery)      1450
(Death Knight, Unholy)       1342
(Druid, Restoration)         1217
(Demon Hunter, Devourer)      953
(Evoker, Preservation)        847
(Shaman, Restoration)         837
(Hunter, Marksmanship)        797
(Druid, Feral)                740
(Warlock, Affliction)         717
(Priest, Shadow)              638
(Shaman, Enhancement)         637
(Rogue, Outlaw)               611
(Warrior, Fury)               602
(Demon Hunter, Havoc)         574
(Warlock, Demonology)         511
(Rogue, Assassination)        498
(Druid, Balance)              488
(Shaman, Elemental)           482
(Mage, Fire)                  402
(Warlock, Destruction)        396
(Death Knight, Frost)         373
(Evoker, Devastation)         340
(Hunter, Survival)            333
(Monk, Brewmaster)            241
(Paladin, Protection)         122
(Druid, Guardian)             115
(Mage, Arcane)                 97
(Evoker, Augmentation)         88
(Warrior, Protection)          65
(Death Knight, Blood)          64
(Demon Hunter, Vengeance)      28
Name: count, dtype: int64

In [128]:
check_pvp[check_pvp['key'].duplicated(keep=False)]

,id,lastModified,name,realm,region,class,activeSpecId,race,faction,gender,...,ratioLoseRbg,nombreRecherche,twitch,scoreArena,scoreRBG,estimatedArenaRank1,estimatedBattlegroundRank1,accountAlgo,ranking,key
13249,7589991,1775846814,Skuggebrewc,Tarren Mill,eu,5,"(Priest, Shadow)",28,0,0,...,0,45,NaN,1729,860,False,False,7589991,13241,eu_Tarren Mill_Skuggebrewc
13250,7589990,1775846814,Skuggebrewc,Tarren Mill,eu,5,"(Priest, Shadow)",28,0,0,...,0,52,NaN,1729,860,False,False,7589990,13241,eu_Tarren Mill_Skuggebrewc
38110,7598794,1775948692,Tháñatos,Ravencrest,eu,6,"(Death Knight, Unholy)",3,1,0,...,0,1,NaN,350,0,False,False,7598794,37824,eu_Ravencrest_Tháñatos
38111,7598793,1775948692,Tháñatos,Ravencrest,eu,6,"(Death Knight, Unholy)",3,1,0,...,0,6,NaN,350,0,False,False,7598794,37824,eu_Ravencrest_Tháñatos

# Blizz API

In [27]:
combine = pd.read_parquet('data/processed/pvp_players.parquet')
combine['class_spec'] = combine['class_name'] + ' ' + combine['spec_name']
combine

,player_key,region,character_name,realm,realm_slug,class_name,spec_name,shuffle_class_name,shuffle_spec_name,blitz_class_name,blitz_spec_name,shuffle_rating,blitz_rating,rating_2v2,rating_3v3,rating_rbg,class_spec
0,eu|ravencrest|feetup,eu,Feetup,Ravencrest,ravencrest,Druid,Restoration,Druid,Restoration,Druid,Restoration,1908,288,2096,2669,0,Druid Restoration
1,us|drenden|dankdad,us,Dankdad,Drenden,drenden,Rogue,Outlaw,Rogue,Outlaw,,,2151,<NA>,1791,2661,0,Rogue Outlaw
2,eu|kazzak|mâroxd,eu,Mâroxd,Kazzak,kazzak,Mage,Frost,Mage,Frost,Mage,Frost,2548,1836,1920,2643,0,Mage Frost
3,us|zuljin|magnuszx,us,Magnuszx,Zul'jin,zuljin,Warrior,Arms,Warrior,Arms,Warrior,Arms,2392,1414,2283,2637,0,Warrior Arms
4,eu|tarren-mill|cocojonsito,eu,Cocojonsito,Tarren Mill,tarren-mill,Monk,Mistweaver,Monk,Mistweaver,,,2330,<NA>,1658,2630,0,Monk Mistweaver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384375,us|zuljin|jehli,us,Jehli,zuljin,zuljin,Paladin,Protection,,,,,<NA>,<NA>,<NA>,<NA>,192,Paladin Protection
384376,eu|dragonblight|deadnog,eu,Deadnog,dragonblight,dragonblight,Death Knight,Unholy,,,,,<NA>,<NA>,<NA>,<NA>,191,Death Knight Unholy
384377,eu|ravencrest|plouxira,eu,Plouxira,ravencrest,ravencrest,Shaman,Elemental,,,,,<NA>,<NA>,<NA>,<NA>,191,Shaman Elemental
384378,eu|silvermoon|jarms,eu,Jarms,silvermoon,silvermoon,Paladin,Retribution,,,,,<NA>,<NA>,<NA>,<NA>,191,Paladin Retribution
384379,eu|turalyon|darthbalodya,eu,Darthbalodya,turalyon,turalyon,Warlock,Demonology,,,,,<NA>,<NA>,<NA>,<NA>,191,Warlock Demonology

In [52]:
combine[combine['rating_3v3'] > 0]

,player_key,region,character_name,realm,realm_slug,class_name,spec_name,shuffle_class_name,shuffle_spec_name,blitz_class_name,blitz_spec_name,shuffle_rating,blitz_rating,rating_2v2,rating_3v3,rating_rbg,class_spec
0,eu|ravencrest|feetup,eu,Feetup,Ravencrest,ravencrest,Druid,Restoration,Druid,Restoration,Druid,Restoration,1908,288,2096,2669,0,Druid Restoration
1,us|drenden|dankdad,us,Dankdad,Drenden,drenden,Rogue,Outlaw,Rogue,Outlaw,,,2151,<NA>,1791,2661,0,Rogue Outlaw
2,eu|kazzak|mâroxd,eu,Mâroxd,Kazzak,kazzak,Mage,Frost,Mage,Frost,Mage,Frost,2548,1836,1920,2643,0,Mage Frost
3,us|zuljin|magnuszx,us,Magnuszx,Zul'jin,zuljin,Warrior,Arms,Warrior,Arms,Warrior,Arms,2392,1414,2283,2637,0,Warrior Arms
4,eu|tarren-mill|cocojonsito,eu,Cocojonsito,Tarren Mill,tarren-mill,Monk,Mistweaver,Monk,Mistweaver,,,2330,<NA>,1658,2630,0,Monk Mistweaver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79059,eu|tarren-mill|karti,eu,Karti,Tarren Mill,tarren-mill,Demon Hunter,Devourer,,,,,<NA>,<NA>,96,95,0,Demon Hunter Devourer
79060,eu|draenor|hîkami,eu,Hîkami,Draenor,draenor,Mage,Fire,,,,,<NA>,<NA>,95,95,0,Mage Fire
79061,eu|blackmoore|schwermut,eu,Schwermut,Blackmoore,blackmoore,Death Knight,Blood,,,,,<NA>,<NA>,0,95,0,Death Knight Blood
79062,eu|colinas-pardas|cirdam,eu,Cirdam,Colinas Pardas,colinas-pardas,Warlock,Demonology,,,,,<NA>,<NA>,0,95,0,Warlock Demonology
79063,eu|khaz-modan|toxicd,eu,Toxicd,Khaz Modan,khaz-modan,Paladin,Protection,,,,,<NA>,<NA>,0,95,0,Paladin Protection

In [80]:
import plotly.graph_objects as go

specs = violins.groupby('class_spec')[col].median().sort_values().index
fig = go.Figure()

for spec in specs:
    mask = violins['class_spec'] == spec
    n_obs = mask.sum()
    if n_obs < 100:
        continue

    fig.add_trace(go.Violin(x=violins['class_spec'][mask],
                            y=violins[col][mask],
                            name=f"{spec}<br>n={n_obs}",
                            box_visible=True,
                            meanline_visible=True),
                  )
fig.update_layout(template="plotly_dark")
fig.write_html('test.html', auto_open=False)

# Blizzard RGB

In [19]:
df = pd.read_parquet('data/raw/blizzard_eu_season_41.parquet')
df

,player_key,region,realm_slug,realm,character_name,class_name,spec_name,mode,rating,rank,season_id,leaderboard,played,won,lost
0,eu|outland|àkròlolz,eu,outland,outland,Àkròlolz,,,2v2,2348,1,41,2v2,121,103,18
1,eu|ravencrest|azizlagardav,eu,ravencrest,ravencrest,Azizlagardav,,,2v2,2348,1,41,2v2,644,374,270
2,eu|dentarg|fusetonww,eu,dentarg,dentarg,Fusetonww,,,2v2,2327,3,41,2v2,115,87,28
3,eu|archimonde|langneur,eu,archimonde,archimonde,Langneur,,,2v2,2317,4,41,2v2,78,71,7
4,eu|ravencrest|despãirx,eu,ravencrest,ravencrest,Despãirx,,,2v2,2304,5,41,2v2,152,105,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251383,eu|ravencrest|evelinee,eu,ravencrest,ravencrest,Evelinee,Warrior,Fury,blitz,138,3532,41,blitz-warrior-fury,3,1,2
251384,eu|howling-fjord|хагарт,eu,howling-fjord,howling-fjord,Хагарт,Warrior,Fury,blitz,138,3532,41,blitz-warrior-fury,3,1,2
251385,eu|silvermoon|themanjohn,eu,silvermoon,silvermoon,Themanjohn,Warrior,Fury,blitz,138,3532,41,blitz-warrior-fury,4,1,3
251386,eu|sanguino|ansiolythicc,eu,sanguino,sanguino,Ansiolythicc,Warrior,Fury,blitz,138,3532,41,blitz-warrior-fury,5,1,4
251387,eu|blackmoore|shødana,eu,blackmoore,blackmoore,Shødana,Warrior,Fury,blitz,138,3532,41,blitz-warrior-fury,7,1,6

In [22]:
df['mode'].value_counts()

mode
shuffle    140110
blitz       97935
3v3          5008
2v2          5003
rbg          3332
Name: count, dtype: int64